services:
  nginx:
    image: nginx:latest
    container_name: formalismysql-nginx
    ports:
      - "8080:80"
      - "8443:443"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - ./ssl:/etc/nginx/ssl
    depends_on:
      - node-app

  node-app:
    image: formalis-node-app
    container_name: formalis-node
    build:
      context: ../node-app
    ports:
      - "3000:3000"
    depends_on:
      - mysql

  mysql:
    image: mysql:8
    container_name: formalismysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: formalis
    ports:
      - "3306:3306"
    volumes:
      - ../mysql/mysql-data:/var/lib/mysql
